### ISSUE TITLE
Please confirm the universal endpoint that can be used for confomance tests

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/areadesenvolvedor#174]
We understand the /resources/v1/resources API is mandatory for all consents, alternatively the /customers/v1/personal/identifications could be used.

Please advise which should be used as the standard endpoint for conformance testing.

**Comment by EkkeErick** [comment]
The security conformance test is held by the Open ID Foundation and not the Open Banking Brazil. 

Could you please direct this question to the OIDF via: certificate@oidf.org

**Comment by jogu** [comment]
As per communication we received from mirow, OIDF expect to deploy a change tomorrow that will allow the resources endpoint to be used instead of the accounts endpoint.

https://gitlab.com/openid/conformance-suite/-/releases will be updated once the new release with that change is deployed to the production certification server.

It anyone runs into a problem they can contact certification@oidf.org or raise an issue at https://gitlab.com/openid/conformance-suite/-/issues/new
